# Generated by Django 2.2.4 on 2019-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=1024)),
                ('publish', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
